spring:
  config:
    import: optional:file:.env[.properties] # 외부에서 env 주입하는 구조 만들기 전까지는 임시로 .env 강제주입

  application:
    name: mini-project

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  flyway:
    enabled: true
    baseline-on-migrate: false

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite-preview
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.4-mini