CREATE TYPE GENDER_ENUM AS ENUM('M','F');

CREATE TABLE member
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    login_id   VARCHAR(255)                            NOT NULL,
    gender     GENDER_ENUM,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE TABLE member_post_link
(
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    memo       VARCHAR(255),
    member_id  BIGINT       NOT NULL,
    post_id    VARCHAR(255) NOT NULL,
    CONSTRAINT pk_member_post_link PRIMARY KEY (member_id, post_id)
);

CREATE TABLE post
(
    id          VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

ALTER TABLE member
    ADD CONSTRAINT uc_member_loginid UNIQUE (login_id);

ALTER TABLE member_post_link
    ADD CONSTRAINT FK_MEMBER_POST_LINK_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE;

CREATE INDEX ix_userpostlink_member_id ON member_post_link (member_id);

ALTER TABLE member_post_link
    ADD CONSTRAINT FK_MEMBER_POST_LINK_ON_POST FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE;

CREATE INDEX ix_userpostlink_post_id ON member_post_link (post_id);